<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="sacvd04135" name="com.bsc.qa.facets.afa.test.BorFileValidationTest" tests="19" failures="2" timestamp="18 Jun 2019 12:36:52 GMT" time="0.312" errors="1">
  <testcase name="testAllData" time="0.003" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testAllData" time="0.265" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.002" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testAllData" time="0.003" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.002" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.001" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.bsc.qa.facets.afa.test.BorFileValidationTest.testBorToDBData(BorFileValidationTest.java:345)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
at com.bsc.qa.facets.afa.test.BorFileValidationTest.run(BorFileValidationTest.java:462)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:576)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testBorToDBData -->
  <testcase name="testBorToDBData" time="0.004" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.002" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.004" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	CLM_AMT mismatch for claimID - 101993660018,01 expected [117.00] but found [-106.82]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
CLM_AMT mismatch for claimID - 101993660018,01 expected [117.00] but found [-106.82]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.bsc.qa.facets.afa.test.BorFileValidationTest.testBorToDBData(BorFileValidationTest.java:397)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
at com.bsc.qa.facets.afa.test.BorFileValidationTest.run(BorFileValidationTest.java:462)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:576)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testBorToDBData -->
  <testcase name="testAllData" time="0.002" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.000" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.002" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.001" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	CLM_AMT mismatch for claimID - 192488723848,01 expected [16.00] but found [-50.00]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
CLM_AMT mismatch for claimID - 192488723848,01 expected [16.00] but found [-50.00]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.bsc.qa.facets.afa.test.BorFileValidationTest.testBorToDBData(BorFileValidationTest.java:397)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
at com.bsc.qa.facets.afa.test.BorFileValidationTest.run(BorFileValidationTest.java:462)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:576)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testBorToDBData -->
  <testcase name="testAllData" time="0.003" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testAllData" time="0.003" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.001" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testAllData" time="0.006" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.002" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
  <testcase name="testBorToDBData" time="0.006" classname="com.bsc.qa.facets.afa.test.BorFileValidationTest"/>
</testsuite> <!-- com.bsc.qa.facets.afa.test.BorFileValidationTest -->
