<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sacvd04320" ignored="0" name="Default test" tests="33" failures="6" timestamp="04 Jun 2019 08:47:48 GMT" time="1.96" errors="0">
  <testcase name="testAddLine1" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testAddLine1 -->
  <testcase name="testAddLine2" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testAddLine2 -->
  <testcase name="testCity" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testCity -->
  <testcase name="testCountyCd" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testCountyCd -->
  <testcase name="testEffDt" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testEffDt -->
  <testcase name="testFax" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testFax -->
  <testcase name="testFedTaxID" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testFedTaxID -->
  <testcase name="testHospital" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testHospital -->
  <testcase name="testMedicareNum" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testMedicareNum -->
  <testcase name="testNPI" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testNPI -->
  <testcase name="testParentNPI" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testParentNPI -->
  <testcase name="testPhone" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testPhone -->
  <testcase name="testPhoneExtension" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testPhoneExtension -->
  <testcase name="testPlanCd" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testPlanCd -->
  <testcase name="testProduct" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testProduct -->
  <testcase name="testProvType" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testProvType -->
  <testcase name="testSiteID" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testSiteID -->
  <testcase name="testState" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testState -->
  <testcase name="testTaxonomy1" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testTaxonomy1 -->
  <testcase name="testTaxonomy2" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testTaxonomy2 -->
  <testcase name="testTaxonomy3" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testTaxonomy3 -->
  <testcase name="testTaxonomy4" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testTaxonomy4 -->
  <testcase name="testTaxonomy5" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testTaxonomy5 -->
  <testcase name="testTaxonomy6" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testTaxonomy6 -->
  <testcase name="testTaxonomy7" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testTaxonomy7 -->
  <testcase name="testTermDt" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testTermDt -->
  <testcase name="testTranstype" time="0.285" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	No Data">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	No Data
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.bsc.qa.facets.ffp.test.HospitalTest.testTranstype(HospitalTest.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:209)
	at com.bsc.qa.facets.ffp.test.HospitalTest.run(HospitalTest.java:1435)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testTranstype -->
  <testcase name="testTranstype" time="0.002" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	No Data">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	No Data
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.bsc.qa.facets.ffp.test.HospitalTest.testTranstype(HospitalTest.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:209)
	at com.bsc.qa.facets.ffp.test.HospitalTest.run(HospitalTest.java:1435)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testTranstype -->
  <testcase name="testTranstype" time="0.003" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	No Data">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	No Data
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.bsc.qa.facets.ffp.test.HospitalTest.testTranstype(HospitalTest.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:209)
	at com.bsc.qa.facets.ffp.test.HospitalTest.run(HospitalTest.java:1435)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testTranstype -->
  <testcase name="testTranstype" time="0.002" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	No Data">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	No Data
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.bsc.qa.facets.ffp.test.HospitalTest.testTranstype(HospitalTest.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:209)
	at com.bsc.qa.facets.ffp.test.HospitalTest.run(HospitalTest.java:1435)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testTranstype -->
  <testcase name="testTranstype" time="0.001" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	No Data">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	No Data
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.bsc.qa.facets.ffp.test.HospitalTest.testTranstype(HospitalTest.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:209)
	at com.bsc.qa.facets.ffp.test.HospitalTest.run(HospitalTest.java:1435)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testTranstype -->
  <testcase name="testTranstype" time="0.002" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	No Data">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	No Data
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.bsc.qa.facets.ffp.test.HospitalTest.testTranstype(HospitalTest.java:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:209)
	at com.bsc.qa.facets.ffp.test.HospitalTest.run(HospitalTest.java:1435)
	at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:221)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:657)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testTranstype -->
  <testcase name="testZip" time="0.0" classname="com.bsc.qa.facets.ffp.test.HospitalTest">
    <skipped/>
  </testcase> <!-- testZip -->
</testsuite> <!-- Default test -->
